// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.20.3
// source: loan_calculator/v1/calculation.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CalculationService_CalculateMonthlyRepayment_FullMethodName = "/loan_calculator.v1.CalculationService/CalculateMonthlyRepayment"
)

// CalculationServiceClient is the client API for CalculationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CalculationServiceClient interface {
	CalculateMonthlyRepayment(ctx context.Context, in *CalculateMonthlyRepaymentRequest, opts ...grpc.CallOption) (*CalculateMonthlyRepaymentResponse, error)
}

type calculationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCalculationServiceClient(cc grpc.ClientConnInterface) CalculationServiceClient {
	return &calculationServiceClient{cc}
}

func (c *calculationServiceClient) CalculateMonthlyRepayment(ctx context.Context, in *CalculateMonthlyRepaymentRequest, opts ...grpc.CallOption) (*CalculateMonthlyRepaymentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CalculateMonthlyRepaymentResponse)
	err := c.cc.Invoke(ctx, CalculationService_CalculateMonthlyRepayment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CalculationServiceServer is the server API for CalculationService service.
// All implementations must embed UnimplementedCalculationServiceServer
// for forward compatibility.
type CalculationServiceServer interface {
	CalculateMonthlyRepayment(context.Context, *CalculateMonthlyRepaymentRequest) (*CalculateMonthlyRepaymentResponse, error)
	mustEmbedUnimplementedCalculationServiceServer()
}

// UnimplementedCalculationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCalculationServiceServer struct{}

func (UnimplementedCalculationServiceServer) CalculateMonthlyRepayment(context.Context, *CalculateMonthlyRepaymentRequest) (*CalculateMonthlyRepaymentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CalculateMonthlyRepayment not implemented")
}
func (UnimplementedCalculationServiceServer) mustEmbedUnimplementedCalculationServiceServer() {}
func (UnimplementedCalculationServiceServer) testEmbeddedByValue()                            {}

// UnsafeCalculationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CalculationServiceServer will
// result in compilation errors.
type UnsafeCalculationServiceServer interface {
	mustEmbedUnimplementedCalculationServiceServer()
}

func RegisterCalculationServiceServer(s grpc.ServiceRegistrar, srv CalculationServiceServer) {
	// If the following call panics, it indicates UnimplementedCalculationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CalculationService_ServiceDesc, srv)
}

func _CalculationService_CalculateMonthlyRepayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CalculateMonthlyRepaymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalculationServiceServer).CalculateMonthlyRepayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CalculationService_CalculateMonthlyRepayment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalculationServiceServer).CalculateMonthlyRepayment(ctx, req.(*CalculateMonthlyRepaymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CalculationService_ServiceDesc is the grpc.ServiceDesc for CalculationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CalculationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "loan_calculator.v1.CalculationService",
	HandlerType: (*CalculationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CalculateMonthlyRepayment",
			Handler:    _CalculationService_CalculateMonthlyRepayment_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "loan_calculator/v1/calculation.proto",
}
