// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: insert_loan_calculation_request.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const insertLoanCalculationRequest = `-- name: InsertLoanCalculationRequest :one
INSERT INTO loan_calculation_requests (
    id,
    tenant_id, 
    loan_amount, 
    interest_rate, 
    number_of_payments, 
    monthly_repayment_amount
) VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, tenant_id, loan_amount, interest_rate, number_of_payments, monthly_repayment_amount, created_at, updated_at
`

type InsertLoanCalculationRequestParams struct {
	ID                     uuid.UUID
	TenantID               uuid.UUID
	LoanAmount             pgtype.Numeric
	InterestRate           pgtype.Numeric
	NumberOfPayments       int32
	MonthlyRepaymentAmount pgtype.Numeric
}

func (q *Queries) InsertLoanCalculationRequest(ctx context.Context, arg InsertLoanCalculationRequestParams) (LoanCalculationRequest, error) {
	row := q.db.QueryRow(ctx, insertLoanCalculationRequest,
		arg.ID,
		arg.TenantID,
		arg.LoanAmount,
		arg.InterestRate,
		arg.NumberOfPayments,
		arg.MonthlyRepaymentAmount,
	)
	var i LoanCalculationRequest
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.LoanAmount,
		&i.InterestRate,
		&i.NumberOfPayments,
		&i.MonthlyRepaymentAmount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
