// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package database

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type LoanCalculationRequest struct {
	ID                     uuid.UUID
	TenantID               uuid.UUID
	LoanAmount             pgtype.Numeric
	InterestRate           pgtype.Numeric
	NumberOfPayments       int32
	MonthlyRepaymentAmount pgtype.Numeric
	CreatedAt              time.Time
	UpdatedAt              time.Time
}
