// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.20.3
// source: loan_calculator/v1/calculation.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CalculateMonthlyRepaymentRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	LoanAmount       float64                `protobuf:"fixed64,1,opt,name=loan_amount,json=loanAmount,proto3" json:"loan_amount,omitempty"`
	InterestRate     float64                `protobuf:"fixed64,2,opt,name=interest_rate,json=interestRate,proto3" json:"interest_rate,omitempty"`
	NumberOfPayments int32                  `protobuf:"varint,3,opt,name=number_of_payments,json=numberOfPayments,proto3" json:"number_of_payments,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CalculateMonthlyRepaymentRequest) Reset() {
	*x = CalculateMonthlyRepaymentRequest{}
	mi := &file_loan_calculator_v1_calculation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculateMonthlyRepaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculateMonthlyRepaymentRequest) ProtoMessage() {}

func (x *CalculateMonthlyRepaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_loan_calculator_v1_calculation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculateMonthlyRepaymentRequest.ProtoReflect.Descriptor instead.
func (*CalculateMonthlyRepaymentRequest) Descriptor() ([]byte, []int) {
	return file_loan_calculator_v1_calculation_proto_rawDescGZIP(), []int{0}
}

func (x *CalculateMonthlyRepaymentRequest) GetLoanAmount() float64 {
	if x != nil {
		return x.LoanAmount
	}
	return 0
}

func (x *CalculateMonthlyRepaymentRequest) GetInterestRate() float64 {
	if x != nil {
		return x.InterestRate
	}
	return 0
}

func (x *CalculateMonthlyRepaymentRequest) GetNumberOfPayments() int32 {
	if x != nil {
		return x.NumberOfPayments
	}
	return 0
}

type CalculateMonthlyRepaymentResponse struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Id                     string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	MonthlyRepaymentAmount float64                `protobuf:"fixed64,2,opt,name=monthly_repayment_amount,json=monthlyRepaymentAmount,proto3" json:"monthly_repayment_amount,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *CalculateMonthlyRepaymentResponse) Reset() {
	*x = CalculateMonthlyRepaymentResponse{}
	mi := &file_loan_calculator_v1_calculation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculateMonthlyRepaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculateMonthlyRepaymentResponse) ProtoMessage() {}

func (x *CalculateMonthlyRepaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_loan_calculator_v1_calculation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculateMonthlyRepaymentResponse.ProtoReflect.Descriptor instead.
func (*CalculateMonthlyRepaymentResponse) Descriptor() ([]byte, []int) {
	return file_loan_calculator_v1_calculation_proto_rawDescGZIP(), []int{1}
}

func (x *CalculateMonthlyRepaymentResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CalculateMonthlyRepaymentResponse) GetMonthlyRepaymentAmount() float64 {
	if x != nil {
		return x.MonthlyRepaymentAmount
	}
	return 0
}

var File_loan_calculator_v1_calculation_proto protoreflect.FileDescriptor

const file_loan_calculator_v1_calculation_proto_rawDesc = "" +
	"\n" +
	"$loan_calculator/v1/calculation.proto\x12\x12loan_calculator.v1\x1a\x1cgoogle/api/annotations.proto\"\x96\x01\n" +
	" CalculateMonthlyRepaymentRequest\x12\x1f\n" +
	"\vloan_amount\x18\x01 \x01(\x01R\n" +
	"loanAmount\x12#\n" +
	"\rinterest_rate\x18\x02 \x01(\x01R\finterestRate\x12,\n" +
	"\x12number_of_payments\x18\x03 \x01(\x05R\x10numberOfPayments\"m\n" +
	"!CalculateMonthlyRepaymentResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x128\n" +
	"\x18monthly_repayment_amount\x18\x02 \x01(\x01R\x16monthlyRepaymentAmount2\xcc\x01\n" +
	"\x12CalculationService\x12\xb5\x01\n" +
	"\x19CalculateMonthlyRepayment\x124.loan_calculator.v1.CalculateMonthlyRepaymentRequest\x1a5.loan_calculator.v1.CalculateMonthlyRepaymentResponse\"+\x82\xd3\xe4\x93\x02%:\x01*\" /v1/monthly-repayments/calculateBSZQgithub.com/tugascript/loan_calculator/calculation_api/proto/loan_calculator/v1;v1b\x06proto3"

var (
	file_loan_calculator_v1_calculation_proto_rawDescOnce sync.Once
	file_loan_calculator_v1_calculation_proto_rawDescData []byte
)

func file_loan_calculator_v1_calculation_proto_rawDescGZIP() []byte {
	file_loan_calculator_v1_calculation_proto_rawDescOnce.Do(func() {
		file_loan_calculator_v1_calculation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_loan_calculator_v1_calculation_proto_rawDesc), len(file_loan_calculator_v1_calculation_proto_rawDesc)))
	})
	return file_loan_calculator_v1_calculation_proto_rawDescData
}

var file_loan_calculator_v1_calculation_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_loan_calculator_v1_calculation_proto_goTypes = []any{
	(*CalculateMonthlyRepaymentRequest)(nil),  // 0: loan_calculator.v1.CalculateMonthlyRepaymentRequest
	(*CalculateMonthlyRepaymentResponse)(nil), // 1: loan_calculator.v1.CalculateMonthlyRepaymentResponse
}
var file_loan_calculator_v1_calculation_proto_depIdxs = []int32{
	0, // 0: loan_calculator.v1.CalculationService.CalculateMonthlyRepayment:input_type -> loan_calculator.v1.CalculateMonthlyRepaymentRequest
	1, // 1: loan_calculator.v1.CalculationService.CalculateMonthlyRepayment:output_type -> loan_calculator.v1.CalculateMonthlyRepaymentResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_loan_calculator_v1_calculation_proto_init() }
func file_loan_calculator_v1_calculation_proto_init() {
	if File_loan_calculator_v1_calculation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_loan_calculator_v1_calculation_proto_rawDesc), len(file_loan_calculator_v1_calculation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_loan_calculator_v1_calculation_proto_goTypes,
		DependencyIndexes: file_loan_calculator_v1_calculation_proto_depIdxs,
		MessageInfos:      file_loan_calculator_v1_calculation_proto_msgTypes,
	}.Build()
	File_loan_calculator_v1_calculation_proto = out.File
	file_loan_calculator_v1_calculation_proto_goTypes = nil
	file_loan_calculator_v1_calculation_proto_depIdxs = nil
}
